
print("*" * 150)
gpa = [ 4.0, 3.9, 3.8, 3.7, 3.6, 3.5, 3.4, 3.3, 3.2, 3.1, 3.0, 2.9, 2.8, 2.7, 2.6, 2.5, 2.4,
       2.3, 2.2, 2.1, 2.0, 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0]
print("##please choose your letter grade from the list..".upper())
print(gpa)
print("*" * 150)
grade = float(input("please enter your gba:".upper()))
if grade == 4:
    print(" 'A+' and your grade starts from 95>>100 GO ON MAN.. ")
elif grade == 3.9:
    print(" 'A' and your grade starts from 94")
elif grade == 3.8:
    print(" 'A' and your grade starts from 93")
elif grade == 3.7:
    print(" 'A' and your grade starts from 92")
elif grade == 3.6:
    print(" 'A' and your grade starts from 91")
elif grade == 3.5:
    print(" 'A' and your grade starts from 90")
elif grade == 3.4:
    print(" 'B+' and your grade starts from 89")
elif grade == 3.3:
    print(" 'B' and your grade starts from 88")
elif grade == 3.2:
    print(" 'B' and your grade starts from 87")
elif grade == 3.1:
    print(" 'B' and your grade starts from 86")
elif grade == 3.0:
    print(" 'B' and your grade starts from 85")
elif grade == 2.9:
    print(" 'B' and your grade starts from 84")
elif grade == 2.8:
    print(" 'B' and your grade starts from 83")
elif grade == 2.7:
    print(" 'B'and your grade starts from 82")
elif grade == 2.6:
    print(" 'B' and your grade starts from 81")
elif grade == 2.5:
    print(" 'B' and your grade starts from 80")
elif grade == 2.4:
    print(" 'C' and your grade starts from 79")
elif grade == 2.3:
    print(" 'C' and your grade starts from 78")
elif grade == 2.2:
    print(" 'C' and your grade starts from 77")
elif grade == 2.1:
    print(" 'C' and your grade starts from 76")
elif grade == 2.0:
    print(" 'C' and your grade starts from 75")
elif grade == 1.9:
    print(" 'C' and your grade starts from 74")
elif grade == 1.8:
    print(" 'C' and your grade starts from 73")
elif grade == 1.7:
    print(" 'C-' and your grade starts from 72")
elif grade == 1.6:
    print(" 'C' and your grade starts from 71")
elif grade == 1.5:
    print(" 'C' and your grade starts from 70")
elif grade == 1.4:
    print(" 'D+' and your grade starts from 69")
elif grade == 1.3:
    print(" 'D' and your grade starts from 68")
elif grade == 1.2:
    print(" 'D' and your grade starts from 67")
elif grade == 1.1:
    print(" 'D' and your grade starts from 66")
elif grade == 1.0:
    print(" 'D' and your grade starts from 65")
elif grade == 0.9:
    print(" 'D' and your grade starts from 64")
elif grade == 0.8:
    print(" 'D' and your grade starts from 63")
elif grade == 0.7:
    print(" 'D' and your grade starts from 62")
elif grade == 0.6:
    print(" 'D' and your grade starts from 61")
elif grade == 0.5:
    print(" 'D' and your grade starts from 60")
elif grade == 0.4:
    print(" 'D' and your grade starts from 59")
elif grade == 0.3:
    print(" 'D' and your grade starts from 58")
elif grade == 0.2:
    print(" 'D' and your grade starts from 57")
elif grade == 0.1:
    print(" 'D' and your grade starts from 56")
elif grade == 0.0:
    print(" 'F' and your grade starts from 55")
else:
    print("please chouse your gpa from the list:")
